### PR TITLE
Python3 Support

### PR DESCRIPTION
**Pull request by Cabalist**
This is a first pass at including Python3 support (and keeping Python2).  I'm still working on reviewing that there aren't any regressions but I thought I would put out a request for feedback.  

There should be no functionality changes just formatting and Python3 support.  

I added the test data to the repository to ease future testing.  I don't believe there should be any license issues given the length of the samples.

### CODE REVIEW

**Comment by Hellowlol** [comment]
This is really good stuff. I tried to port it but I got funky numpy that I didn’t understand. I’ll send a or so windows are supported and remove all the print statements (use logging instead)

**Comment by Hellowlol** [comment]
While we’re at it we should turn this into a proper package so we can install it with pip with a cli entry point

**Comment by Cabalist** [comment]
Heh.  Yeah that is why I started.  I saw your project on r/plex  :)

Please test!  I am writing my own tests here but getting some feedback would be great.  

Your numpy error was probably related to the changes with division in Py3.  In Python 2 division was type dependent.

```
3/2 => 1
3/2.0 => 1.5
```
  
In Python3 it was made much more consistent

```
3/2 => 1.5
3/2.0 => 1.5
```

However there were a couple places in the code that were dependent on the division always returning an int.   You can accomplish this in Python 3 by using `//` instead of `/` and making sure you use `from __future__ import division` to maintain backward compatibility.

**Comment by Hellowlol** [comment]
I will. 🙏

**Comment by Hellowlol** [comment]
@dpwe Can this be merged? It would be really nice to use py3 for my project.

**Comment by dpwe** [comment]
Sorry for the delay.  Many thanks, @Cabalist - nice job.

**Pull request merged**
